// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: chatService.proto

#include "chatService.pb.h"
#include "chatService.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace chatservice {

static const char* ChatService_method_names[] = {
  "/chatservice.ChatService/CreateAccount",
  "/chatservice.ChatService/Login",
  "/chatservice.ChatService/Logout",
  "/chatservice.ChatService/ListUsers",
  "/chatservice.ChatService/SendMessage",
  "/chatservice.ChatService/QueryNotifications",
  "/chatservice.ChatService/QueryMessages",
  "/chatservice.ChatService/DeleteAccount",
  "/chatservice.ChatService/RefreshClient",
  "/chatservice.ChatService/Commit",
  "/chatservice.ChatService/HeartBeat",
  "/chatservice.ChatService/SuggestLeaderElection",
  "/chatservice.ChatService/LeaderElection",
  "/chatservice.ChatService/AddToPending",
  "/chatservice.ChatService/RequestPendingLog",
  "/chatservice.ChatService/MessagesSeen",
};

std::unique_ptr< ChatService::Stub> ChatService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ChatService::Stub> stub(new ChatService::Stub(channel, options));
  return stub;
}

ChatService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CreateAccount_(ChatService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Login_(ChatService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Logout_(ChatService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListUsers_(ChatService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_SendMessage_(ChatService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_QueryNotifications_(ChatService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_QueryMessages_(ChatService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_DeleteAccount_(ChatService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RefreshClient_(ChatService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Commit_(ChatService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_HeartBeat_(ChatService_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SuggestLeaderElection_(ChatService_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_LeaderElection_(ChatService_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AddToPending_(ChatService_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  , rpcmethod_RequestPendingLog_(ChatService_method_names[14], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_MessagesSeen_(ChatService_method_names[15], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ChatService::Stub::CreateAccount(::grpc::ClientContext* context, const ::chatservice::CreateAccountMessage& request, ::chatservice::CreateAccountReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chatservice::CreateAccountMessage, ::chatservice::CreateAccountReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateAccount_, context, request, response);
}

void ChatService::Stub::async::CreateAccount(::grpc::ClientContext* context, const ::chatservice::CreateAccountMessage* request, ::chatservice::CreateAccountReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chatservice::CreateAccountMessage, ::chatservice::CreateAccountReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateAccount_, context, request, response, std::move(f));
}

void ChatService::Stub::async::CreateAccount(::grpc::ClientContext* context, const ::chatservice::CreateAccountMessage* request, ::chatservice::CreateAccountReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateAccount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chatservice::CreateAccountReply>* ChatService::Stub::PrepareAsyncCreateAccountRaw(::grpc::ClientContext* context, const ::chatservice::CreateAccountMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chatservice::CreateAccountReply, ::chatservice::CreateAccountMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateAccount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chatservice::CreateAccountReply>* ChatService::Stub::AsyncCreateAccountRaw(::grpc::ClientContext* context, const ::chatservice::CreateAccountMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateAccountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ChatService::Stub::Login(::grpc::ClientContext* context, const ::chatservice::LoginMessage& request, ::chatservice::LoginReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chatservice::LoginMessage, ::chatservice::LoginReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Login_, context, request, response);
}

void ChatService::Stub::async::Login(::grpc::ClientContext* context, const ::chatservice::LoginMessage* request, ::chatservice::LoginReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chatservice::LoginMessage, ::chatservice::LoginReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

void ChatService::Stub::async::Login(::grpc::ClientContext* context, const ::chatservice::LoginMessage* request, ::chatservice::LoginReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chatservice::LoginReply>* ChatService::Stub::PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::chatservice::LoginMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chatservice::LoginReply, ::chatservice::LoginMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Login_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chatservice::LoginReply>* ChatService::Stub::AsyncLoginRaw(::grpc::ClientContext* context, const ::chatservice::LoginMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoginRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ChatService::Stub::Logout(::grpc::ClientContext* context, const ::chatservice::LogoutMessage& request, ::chatservice::LogoutReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chatservice::LogoutMessage, ::chatservice::LogoutReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Logout_, context, request, response);
}

void ChatService::Stub::async::Logout(::grpc::ClientContext* context, const ::chatservice::LogoutMessage* request, ::chatservice::LogoutReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chatservice::LogoutMessage, ::chatservice::LogoutReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Logout_, context, request, response, std::move(f));
}

void ChatService::Stub::async::Logout(::grpc::ClientContext* context, const ::chatservice::LogoutMessage* request, ::chatservice::LogoutReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Logout_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chatservice::LogoutReply>* ChatService::Stub::PrepareAsyncLogoutRaw(::grpc::ClientContext* context, const ::chatservice::LogoutMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chatservice::LogoutReply, ::chatservice::LogoutMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Logout_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chatservice::LogoutReply>* ChatService::Stub::AsyncLogoutRaw(::grpc::ClientContext* context, const ::chatservice::LogoutMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLogoutRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::chatservice::User>* ChatService::Stub::ListUsersRaw(::grpc::ClientContext* context, const ::chatservice::QueryUsersMessage& request) {
  return ::grpc::internal::ClientReaderFactory< ::chatservice::User>::Create(channel_.get(), rpcmethod_ListUsers_, context, request);
}

void ChatService::Stub::async::ListUsers(::grpc::ClientContext* context, const ::chatservice::QueryUsersMessage* request, ::grpc::ClientReadReactor< ::chatservice::User>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::chatservice::User>::Create(stub_->channel_.get(), stub_->rpcmethod_ListUsers_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::chatservice::User>* ChatService::Stub::AsyncListUsersRaw(::grpc::ClientContext* context, const ::chatservice::QueryUsersMessage& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::chatservice::User>::Create(channel_.get(), cq, rpcmethod_ListUsers_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::chatservice::User>* ChatService::Stub::PrepareAsyncListUsersRaw(::grpc::ClientContext* context, const ::chatservice::QueryUsersMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::chatservice::User>::Create(channel_.get(), cq, rpcmethod_ListUsers_, context, request, false, nullptr);
}

::grpc::Status ChatService::Stub::SendMessage(::grpc::ClientContext* context, const ::chatservice::ChatMessage& request, ::chatservice::SendMessageReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chatservice::ChatMessage, ::chatservice::SendMessageReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendMessage_, context, request, response);
}

void ChatService::Stub::async::SendMessage(::grpc::ClientContext* context, const ::chatservice::ChatMessage* request, ::chatservice::SendMessageReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chatservice::ChatMessage, ::chatservice::SendMessageReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendMessage_, context, request, response, std::move(f));
}

void ChatService::Stub::async::SendMessage(::grpc::ClientContext* context, const ::chatservice::ChatMessage* request, ::chatservice::SendMessageReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendMessage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chatservice::SendMessageReply>* ChatService::Stub::PrepareAsyncSendMessageRaw(::grpc::ClientContext* context, const ::chatservice::ChatMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chatservice::SendMessageReply, ::chatservice::ChatMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendMessage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chatservice::SendMessageReply>* ChatService::Stub::AsyncSendMessageRaw(::grpc::ClientContext* context, const ::chatservice::ChatMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendMessageRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::chatservice::Notification>* ChatService::Stub::QueryNotificationsRaw(::grpc::ClientContext* context, const ::chatservice::QueryNotificationsMessage& request) {
  return ::grpc::internal::ClientReaderFactory< ::chatservice::Notification>::Create(channel_.get(), rpcmethod_QueryNotifications_, context, request);
}

void ChatService::Stub::async::QueryNotifications(::grpc::ClientContext* context, const ::chatservice::QueryNotificationsMessage* request, ::grpc::ClientReadReactor< ::chatservice::Notification>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::chatservice::Notification>::Create(stub_->channel_.get(), stub_->rpcmethod_QueryNotifications_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::chatservice::Notification>* ChatService::Stub::AsyncQueryNotificationsRaw(::grpc::ClientContext* context, const ::chatservice::QueryNotificationsMessage& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::chatservice::Notification>::Create(channel_.get(), cq, rpcmethod_QueryNotifications_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::chatservice::Notification>* ChatService::Stub::PrepareAsyncQueryNotificationsRaw(::grpc::ClientContext* context, const ::chatservice::QueryNotificationsMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::chatservice::Notification>::Create(channel_.get(), cq, rpcmethod_QueryNotifications_, context, request, false, nullptr);
}

::grpc::ClientReader< ::chatservice::ChatMessage>* ChatService::Stub::QueryMessagesRaw(::grpc::ClientContext* context, const ::chatservice::QueryMessagesMessage& request) {
  return ::grpc::internal::ClientReaderFactory< ::chatservice::ChatMessage>::Create(channel_.get(), rpcmethod_QueryMessages_, context, request);
}

void ChatService::Stub::async::QueryMessages(::grpc::ClientContext* context, const ::chatservice::QueryMessagesMessage* request, ::grpc::ClientReadReactor< ::chatservice::ChatMessage>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::chatservice::ChatMessage>::Create(stub_->channel_.get(), stub_->rpcmethod_QueryMessages_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::chatservice::ChatMessage>* ChatService::Stub::AsyncQueryMessagesRaw(::grpc::ClientContext* context, const ::chatservice::QueryMessagesMessage& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::chatservice::ChatMessage>::Create(channel_.get(), cq, rpcmethod_QueryMessages_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::chatservice::ChatMessage>* ChatService::Stub::PrepareAsyncQueryMessagesRaw(::grpc::ClientContext* context, const ::chatservice::QueryMessagesMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::chatservice::ChatMessage>::Create(channel_.get(), cq, rpcmethod_QueryMessages_, context, request, false, nullptr);
}

::grpc::Status ChatService::Stub::DeleteAccount(::grpc::ClientContext* context, const ::chatservice::DeleteAccountMessage& request, ::chatservice::DeleteAccountReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chatservice::DeleteAccountMessage, ::chatservice::DeleteAccountReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteAccount_, context, request, response);
}

void ChatService::Stub::async::DeleteAccount(::grpc::ClientContext* context, const ::chatservice::DeleteAccountMessage* request, ::chatservice::DeleteAccountReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chatservice::DeleteAccountMessage, ::chatservice::DeleteAccountReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteAccount_, context, request, response, std::move(f));
}

void ChatService::Stub::async::DeleteAccount(::grpc::ClientContext* context, const ::chatservice::DeleteAccountMessage* request, ::chatservice::DeleteAccountReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteAccount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chatservice::DeleteAccountReply>* ChatService::Stub::PrepareAsyncDeleteAccountRaw(::grpc::ClientContext* context, const ::chatservice::DeleteAccountMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chatservice::DeleteAccountReply, ::chatservice::DeleteAccountMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteAccount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chatservice::DeleteAccountReply>* ChatService::Stub::AsyncDeleteAccountRaw(::grpc::ClientContext* context, const ::chatservice::DeleteAccountMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteAccountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ChatService::Stub::RefreshClient(::grpc::ClientContext* context, const ::chatservice::RefreshRequest& request, ::chatservice::RefreshResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chatservice::RefreshRequest, ::chatservice::RefreshResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RefreshClient_, context, request, response);
}

void ChatService::Stub::async::RefreshClient(::grpc::ClientContext* context, const ::chatservice::RefreshRequest* request, ::chatservice::RefreshResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chatservice::RefreshRequest, ::chatservice::RefreshResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RefreshClient_, context, request, response, std::move(f));
}

void ChatService::Stub::async::RefreshClient(::grpc::ClientContext* context, const ::chatservice::RefreshRequest* request, ::chatservice::RefreshResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RefreshClient_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chatservice::RefreshResponse>* ChatService::Stub::PrepareAsyncRefreshClientRaw(::grpc::ClientContext* context, const ::chatservice::RefreshRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chatservice::RefreshResponse, ::chatservice::RefreshRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RefreshClient_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chatservice::RefreshResponse>* ChatService::Stub::AsyncRefreshClientRaw(::grpc::ClientContext* context, const ::chatservice::RefreshRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRefreshClientRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ChatService::Stub::Commit(::grpc::ClientContext* context, const ::chatservice::CommitRequest& request, ::chatservice::CommitResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chatservice::CommitRequest, ::chatservice::CommitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Commit_, context, request, response);
}

void ChatService::Stub::async::Commit(::grpc::ClientContext* context, const ::chatservice::CommitRequest* request, ::chatservice::CommitResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chatservice::CommitRequest, ::chatservice::CommitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Commit_, context, request, response, std::move(f));
}

void ChatService::Stub::async::Commit(::grpc::ClientContext* context, const ::chatservice::CommitRequest* request, ::chatservice::CommitResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Commit_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chatservice::CommitResponse>* ChatService::Stub::PrepareAsyncCommitRaw(::grpc::ClientContext* context, const ::chatservice::CommitRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chatservice::CommitResponse, ::chatservice::CommitRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Commit_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chatservice::CommitResponse>* ChatService::Stub::AsyncCommitRaw(::grpc::ClientContext* context, const ::chatservice::CommitRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCommitRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ChatService::Stub::HeartBeat(::grpc::ClientContext* context, const ::chatservice::HeartBeatRequest& request, ::chatservice::HeartBeatResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chatservice::HeartBeatRequest, ::chatservice::HeartBeatResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_HeartBeat_, context, request, response);
}

void ChatService::Stub::async::HeartBeat(::grpc::ClientContext* context, const ::chatservice::HeartBeatRequest* request, ::chatservice::HeartBeatResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chatservice::HeartBeatRequest, ::chatservice::HeartBeatResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HeartBeat_, context, request, response, std::move(f));
}

void ChatService::Stub::async::HeartBeat(::grpc::ClientContext* context, const ::chatservice::HeartBeatRequest* request, ::chatservice::HeartBeatResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HeartBeat_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chatservice::HeartBeatResponse>* ChatService::Stub::PrepareAsyncHeartBeatRaw(::grpc::ClientContext* context, const ::chatservice::HeartBeatRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chatservice::HeartBeatResponse, ::chatservice::HeartBeatRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_HeartBeat_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chatservice::HeartBeatResponse>* ChatService::Stub::AsyncHeartBeatRaw(::grpc::ClientContext* context, const ::chatservice::HeartBeatRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHeartBeatRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ChatService::Stub::SuggestLeaderElection(::grpc::ClientContext* context, const ::chatservice::LeaderElectionProposal& request, ::chatservice::LeaderElectionProposalResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chatservice::LeaderElectionProposal, ::chatservice::LeaderElectionProposalResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SuggestLeaderElection_, context, request, response);
}

void ChatService::Stub::async::SuggestLeaderElection(::grpc::ClientContext* context, const ::chatservice::LeaderElectionProposal* request, ::chatservice::LeaderElectionProposalResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chatservice::LeaderElectionProposal, ::chatservice::LeaderElectionProposalResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SuggestLeaderElection_, context, request, response, std::move(f));
}

void ChatService::Stub::async::SuggestLeaderElection(::grpc::ClientContext* context, const ::chatservice::LeaderElectionProposal* request, ::chatservice::LeaderElectionProposalResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SuggestLeaderElection_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chatservice::LeaderElectionProposalResponse>* ChatService::Stub::PrepareAsyncSuggestLeaderElectionRaw(::grpc::ClientContext* context, const ::chatservice::LeaderElectionProposal& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chatservice::LeaderElectionProposalResponse, ::chatservice::LeaderElectionProposal, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SuggestLeaderElection_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chatservice::LeaderElectionProposalResponse>* ChatService::Stub::AsyncSuggestLeaderElectionRaw(::grpc::ClientContext* context, const ::chatservice::LeaderElectionProposal& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSuggestLeaderElectionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ChatService::Stub::LeaderElection(::grpc::ClientContext* context, const ::chatservice::CandidateValue& request, ::chatservice::LeaderElectionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chatservice::CandidateValue, ::chatservice::LeaderElectionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_LeaderElection_, context, request, response);
}

void ChatService::Stub::async::LeaderElection(::grpc::ClientContext* context, const ::chatservice::CandidateValue* request, ::chatservice::LeaderElectionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chatservice::CandidateValue, ::chatservice::LeaderElectionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LeaderElection_, context, request, response, std::move(f));
}

void ChatService::Stub::async::LeaderElection(::grpc::ClientContext* context, const ::chatservice::CandidateValue* request, ::chatservice::LeaderElectionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LeaderElection_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chatservice::LeaderElectionResponse>* ChatService::Stub::PrepareAsyncLeaderElectionRaw(::grpc::ClientContext* context, const ::chatservice::CandidateValue& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chatservice::LeaderElectionResponse, ::chatservice::CandidateValue, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_LeaderElection_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chatservice::LeaderElectionResponse>* ChatService::Stub::AsyncLeaderElectionRaw(::grpc::ClientContext* context, const ::chatservice::CandidateValue& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLeaderElectionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientWriter< ::chatservice::Operation>* ChatService::Stub::AddToPendingRaw(::grpc::ClientContext* context, ::chatservice::AddToPendingResponse* response) {
  return ::grpc::internal::ClientWriterFactory< ::chatservice::Operation>::Create(channel_.get(), rpcmethod_AddToPending_, context, response);
}

void ChatService::Stub::async::AddToPending(::grpc::ClientContext* context, ::chatservice::AddToPendingResponse* response, ::grpc::ClientWriteReactor< ::chatservice::Operation>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::chatservice::Operation>::Create(stub_->channel_.get(), stub_->rpcmethod_AddToPending_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::chatservice::Operation>* ChatService::Stub::AsyncAddToPendingRaw(::grpc::ClientContext* context, ::chatservice::AddToPendingResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::chatservice::Operation>::Create(channel_.get(), cq, rpcmethod_AddToPending_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::chatservice::Operation>* ChatService::Stub::PrepareAsyncAddToPendingRaw(::grpc::ClientContext* context, ::chatservice::AddToPendingResponse* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::chatservice::Operation>::Create(channel_.get(), cq, rpcmethod_AddToPending_, context, response, false, nullptr);
}

::grpc::ClientReader< ::chatservice::Operation>* ChatService::Stub::RequestPendingLogRaw(::grpc::ClientContext* context, const ::chatservice::PendingLogRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::chatservice::Operation>::Create(channel_.get(), rpcmethod_RequestPendingLog_, context, request);
}

void ChatService::Stub::async::RequestPendingLog(::grpc::ClientContext* context, const ::chatservice::PendingLogRequest* request, ::grpc::ClientReadReactor< ::chatservice::Operation>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::chatservice::Operation>::Create(stub_->channel_.get(), stub_->rpcmethod_RequestPendingLog_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::chatservice::Operation>* ChatService::Stub::AsyncRequestPendingLogRaw(::grpc::ClientContext* context, const ::chatservice::PendingLogRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::chatservice::Operation>::Create(channel_.get(), cq, rpcmethod_RequestPendingLog_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::chatservice::Operation>* ChatService::Stub::PrepareAsyncRequestPendingLogRaw(::grpc::ClientContext* context, const ::chatservice::PendingLogRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::chatservice::Operation>::Create(channel_.get(), cq, rpcmethod_RequestPendingLog_, context, request, false, nullptr);
}

::grpc::Status ChatService::Stub::MessagesSeen(::grpc::ClientContext* context, const ::chatservice::MessagesSeenMessage& request, ::chatservice::MessagesSeenReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chatservice::MessagesSeenMessage, ::chatservice::MessagesSeenReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_MessagesSeen_, context, request, response);
}

void ChatService::Stub::async::MessagesSeen(::grpc::ClientContext* context, const ::chatservice::MessagesSeenMessage* request, ::chatservice::MessagesSeenReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chatservice::MessagesSeenMessage, ::chatservice::MessagesSeenReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MessagesSeen_, context, request, response, std::move(f));
}

void ChatService::Stub::async::MessagesSeen(::grpc::ClientContext* context, const ::chatservice::MessagesSeenMessage* request, ::chatservice::MessagesSeenReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MessagesSeen_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chatservice::MessagesSeenReply>* ChatService::Stub::PrepareAsyncMessagesSeenRaw(::grpc::ClientContext* context, const ::chatservice::MessagesSeenMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chatservice::MessagesSeenReply, ::chatservice::MessagesSeenMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_MessagesSeen_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chatservice::MessagesSeenReply>* ChatService::Stub::AsyncMessagesSeenRaw(::grpc::ClientContext* context, const ::chatservice::MessagesSeenMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncMessagesSeenRaw(context, request, cq);
  result->StartCall();
  return result;
}

ChatService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatService::Service, ::chatservice::CreateAccountMessage, ::chatservice::CreateAccountReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chatservice::CreateAccountMessage* req,
             ::chatservice::CreateAccountReply* resp) {
               return service->CreateAccount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatService::Service, ::chatservice::LoginMessage, ::chatservice::LoginReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chatservice::LoginMessage* req,
             ::chatservice::LoginReply* resp) {
               return service->Login(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatService::Service, ::chatservice::LogoutMessage, ::chatservice::LogoutReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chatservice::LogoutMessage* req,
             ::chatservice::LogoutReply* resp) {
               return service->Logout(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[3],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< ChatService::Service, ::chatservice::QueryUsersMessage, ::chatservice::User>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chatservice::QueryUsersMessage* req,
             ::grpc::ServerWriter<::chatservice::User>* writer) {
               return service->ListUsers(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatService::Service, ::chatservice::ChatMessage, ::chatservice::SendMessageReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chatservice::ChatMessage* req,
             ::chatservice::SendMessageReply* resp) {
               return service->SendMessage(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[5],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< ChatService::Service, ::chatservice::QueryNotificationsMessage, ::chatservice::Notification>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chatservice::QueryNotificationsMessage* req,
             ::grpc::ServerWriter<::chatservice::Notification>* writer) {
               return service->QueryNotifications(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[6],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< ChatService::Service, ::chatservice::QueryMessagesMessage, ::chatservice::ChatMessage>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chatservice::QueryMessagesMessage* req,
             ::grpc::ServerWriter<::chatservice::ChatMessage>* writer) {
               return service->QueryMessages(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatService::Service, ::chatservice::DeleteAccountMessage, ::chatservice::DeleteAccountReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chatservice::DeleteAccountMessage* req,
             ::chatservice::DeleteAccountReply* resp) {
               return service->DeleteAccount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatService::Service, ::chatservice::RefreshRequest, ::chatservice::RefreshResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chatservice::RefreshRequest* req,
             ::chatservice::RefreshResponse* resp) {
               return service->RefreshClient(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatService::Service, ::chatservice::CommitRequest, ::chatservice::CommitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chatservice::CommitRequest* req,
             ::chatservice::CommitResponse* resp) {
               return service->Commit(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatService::Service, ::chatservice::HeartBeatRequest, ::chatservice::HeartBeatResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chatservice::HeartBeatRequest* req,
             ::chatservice::HeartBeatResponse* resp) {
               return service->HeartBeat(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatService::Service, ::chatservice::LeaderElectionProposal, ::chatservice::LeaderElectionProposalResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chatservice::LeaderElectionProposal* req,
             ::chatservice::LeaderElectionProposalResponse* resp) {
               return service->SuggestLeaderElection(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatService::Service, ::chatservice::CandidateValue, ::chatservice::LeaderElectionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chatservice::CandidateValue* req,
             ::chatservice::LeaderElectionResponse* resp) {
               return service->LeaderElection(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[13],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< ChatService::Service, ::chatservice::Operation, ::chatservice::AddToPendingResponse>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::chatservice::Operation>* reader,
             ::chatservice::AddToPendingResponse* resp) {
               return service->AddToPending(ctx, reader, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[14],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< ChatService::Service, ::chatservice::PendingLogRequest, ::chatservice::Operation>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chatservice::PendingLogRequest* req,
             ::grpc::ServerWriter<::chatservice::Operation>* writer) {
               return service->RequestPendingLog(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[15],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatService::Service, ::chatservice::MessagesSeenMessage, ::chatservice::MessagesSeenReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chatservice::MessagesSeenMessage* req,
             ::chatservice::MessagesSeenReply* resp) {
               return service->MessagesSeen(ctx, req, resp);
             }, this)));
}

ChatService::Service::~Service() {
}

::grpc::Status ChatService::Service::CreateAccount(::grpc::ServerContext* context, const ::chatservice::CreateAccountMessage* request, ::chatservice::CreateAccountReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::Login(::grpc::ServerContext* context, const ::chatservice::LoginMessage* request, ::chatservice::LoginReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::Logout(::grpc::ServerContext* context, const ::chatservice::LogoutMessage* request, ::chatservice::LogoutReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::ListUsers(::grpc::ServerContext* context, const ::chatservice::QueryUsersMessage* request, ::grpc::ServerWriter< ::chatservice::User>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::SendMessage(::grpc::ServerContext* context, const ::chatservice::ChatMessage* request, ::chatservice::SendMessageReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::QueryNotifications(::grpc::ServerContext* context, const ::chatservice::QueryNotificationsMessage* request, ::grpc::ServerWriter< ::chatservice::Notification>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::QueryMessages(::grpc::ServerContext* context, const ::chatservice::QueryMessagesMessage* request, ::grpc::ServerWriter< ::chatservice::ChatMessage>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::DeleteAccount(::grpc::ServerContext* context, const ::chatservice::DeleteAccountMessage* request, ::chatservice::DeleteAccountReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::RefreshClient(::grpc::ServerContext* context, const ::chatservice::RefreshRequest* request, ::chatservice::RefreshResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::Commit(::grpc::ServerContext* context, const ::chatservice::CommitRequest* request, ::chatservice::CommitResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::HeartBeat(::grpc::ServerContext* context, const ::chatservice::HeartBeatRequest* request, ::chatservice::HeartBeatResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::SuggestLeaderElection(::grpc::ServerContext* context, const ::chatservice::LeaderElectionProposal* request, ::chatservice::LeaderElectionProposalResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::LeaderElection(::grpc::ServerContext* context, const ::chatservice::CandidateValue* request, ::chatservice::LeaderElectionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::AddToPending(::grpc::ServerContext* context, ::grpc::ServerReader< ::chatservice::Operation>* reader, ::chatservice::AddToPendingResponse* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::RequestPendingLog(::grpc::ServerContext* context, const ::chatservice::PendingLogRequest* request, ::grpc::ServerWriter< ::chatservice::Operation>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::MessagesSeen(::grpc::ServerContext* context, const ::chatservice::MessagesSeenMessage* request, ::chatservice::MessagesSeenReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace chatservice

